name: Test & deploy

on:
    push: 
          branches: main

jobs:
    # unit test
    unit-test:
        runs-on: ubuntu-latest 
        steps: 
             - name: clone repo
               uses: actions/checkout@v7                 

             - name: install dep
               run: npm i
              
             - name: test
               run: npm run test